kafka:
  topic: orderstopicdemo
  bootstrap_server: localhost:9092

mysql:
  host: localhost
  port: 3306
  driver: com.mysql.cj.jdbc.Driver
  database: sales_db
  table: total_sales_by_source_state

cassandra:
  host: localhost
  port: 9042
  keyspace: sales_ks
  table: orders_tbl

jars:
  dir: /home/abraham-pc/Documents/personal_projects/pyspark/lib